SELECT
    p.AMOUNT AS SALARY,
    CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS NAME,
    TIMESTAMPDIFF(YEAR, e.DOB, DATE(p.PAYMENT_TIME)) AS AGE,
    d.DEPARTMENT_NAME
FROM PAYMENTS p
INNER JOIN EMPLOYEE e ON e.EMP_ID = p.EMP_ID
INNER JOIN DEPARTMENT d ON d.DEPARTMENT_ID = e.DEPARTMENT
WHERE EXTRACT(DAY FROM p.PAYMENT_TIME) <> 1
  AND p.AMOUNT = (
      SELECT MAX(p2.AMOUNT)
      FROM PAYMENTS p2
      WHERE EXTRACT(DAY FROM p2.PAYMENT_TIME) <> 1
  );
